version: "3"

# Mais info Aqui: https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD: 'NerdevOps' ## Esolha a senha que quiser Substitua 'NerdevOps'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped