version: "3.0"
services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=
      - META_DESCRIPTION=
      - META_AUTHOR=
      - META_KEYWORDS=
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=
      - OG_TITLE=
      - OG_DESCRIPTION=
      - OG_URL=
      - OG_IMAGE=
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Light
      - FAVICON_URL=
      - AVATAR_URL=
      - AVATAR_2X_URL=
      - AVATAR_ALT=
      - NAME=
      - BIO=
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=YOUTUBE,TWITCH,TWITTER,GITHUB,INSTAGRAM,LINKED_IN,DISCORD,FACEBOOK,TIKTOK,PATREON,GEAR,DOCUMENTATION
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - GITHUB=
      - TWITTER=
      #- INSTAGRAM=
      #- LINKED_IN=
      - YOUTUBE=
      - TWITCH=
      #- DISCORD=
      #- TIKTOK=
      #- FACEBOOK=
      #- PATREON=
      - FOOTER=
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true